config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :users, only: [:new, :index, :create, :show] do
    resources :requests, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :offers, only: [:index, :create, :show, :destroy]
  end

  resources :offers, only: [:index]

  namespace :admin do
    resources :tags, only: [:index, :new, :create, :destroy]
  end

  get '/requests', to: 'requests#request_dashboard'
  get '/requests/:id', to: 'requests#view_request', as: 'view_request'
  post '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  post '/offers/:id/decline', to: 'offers#decline', as: 'decline_offer'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :request

  enum status: ["Pending", "Accepted", "Declined"]
end

app/models/request.rb
class Request < ApplicationRecord
  has_and_belongs_to_many :tags
  has_many :offers
  belongs_to :user

  def time
    start_time.strftime('%l:%M %p')
  end

  def date
    start_time.strftime('%b %-d')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :requests
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :requests
  has_many :offers

  validates :username, presence: true, uniqueness: true

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create!(tag_params)

    redirect_to admin_tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_user?
    current_user && current_user.default?
  end

  def require_login
    render file: "/public/404" unless current_user?
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_user
  before_action :set_offer, only: [:accept, :decline, :destroy]
  before_action :require_login

  def index
    @offers = @user.offers
  end

  def create
    @offer = @user.offers.create!(request_id: params[:request_id],
                                  status: 0
                                 )

    redirect_to requests_path
  end

  def destroy
    @offer.destroy

    redirect_to user_offers_path(@user)
  end

  def accept
    @offer.update! status: 1

    redirect_to user_requests_path(@user)
  end

  def decline
    @offer.update! status: 2

    redirect_to user_requests_path(@user)
  end

  private

  def set_user
    @user = current_user
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :destroy, :edit, :update, :view_request]
  before_action :set_user, except: [:request_dashboard, :view_request]
  before_action :require_login, except: [:request_dashboard, :view_request]

  def index
    @requests = @user.requests
  end

  def new
    @request = Request.new
  end

  def create
    @request = @user.requests.create!(request_params)

    redirect_to user_request_path(@user, @request)
  end

  def show
  end

  def edit
  end

  def update
    @request = @user.requests.update(request_params)

    redirect_to user_request_path(@user, @request)
  end

  def destroy
    @request.destroy

    redirect_to user_requests_path(@user)
  end

  def request_dashboard
    @requests = Request.all
  end

  def view_request

  end

  private

  def request_params
    params.require(:request).permit(:title,
                                    :day,
                                    :start_time,
                                    :duration,
                                    :location,
                                    :description)
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create!(tag_params)

    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      #flash message
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :password,
                                 :first_name,
                                 :last_name,
                                 :slack_handle,
                                 :cohort)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/tags/index.html.erb
<h1> Available Tags: </h1>

<% @tags.each do |tag| %>
  <h3> <%= tag.title %> </h3>
  <%= link_to 'Delete Tag', admin_tag_path(tag), method: "delete", class: 'btn btn-large btn-danger' %>
<% end %>

<%= link_to "Create New Tag", new_admin_tag_path %>

app/views/admin/tags/new.html.erb
<h1> Create a New Tag </h1>


<div class="form">
  <%= form_for(:tag, url: admin_tags_path) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PearingApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/navigation' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/offers/index.html.erb
<h1> You Have Offered To Help With These Requests: </h1>

<div class="offer-container container-fluid">
  <% @offers.each do |offer| %>
  <div class="panel panel-default" class=offer_<%= offer.id %>>
    <div class="panel-heading">
      <h3 class="panel-title">
        <h2><%= offer.request.title %></h2><br>
        <%= link_to "More Info", view_request_path(offer.request), class: 'btn btn-large btn-info'%>
      </h3>
    </div>
    <div class="panel-body">
      <h3> Offer Status: <%= offer.status %> </h3><br>
      <%= button_to "Delete Offer", user_offer_path(offer.user, offer), method: "delete", class: 'btn btn-large btn-danger' %>
    </div>
  </div>
  <% end %>
</div>

app/views/requests/_form.html.erb
<div class="form">
  <%= form_for [@user, @request] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :start_time %>
  <%= f.datetime_local_field :start_time %>
  <br />
  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <br />
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br />
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />
  <%= f.submit %>

  <% end %>
</div>

app/views/requests/edit.html.erb
<h1> Edit Your Request </h1>

<%= render "form" %>

app/views/requests/index.html.erb
<div class="request-index">

  <h1> Your Requests </h1>

  <%= link_to "Create New Request", new_user_request_path, class: 'btn btn-large btn-success' %>

  <div class="request-container container-fluid">
    <% @requests.each do |request| %>
    <div class="panel panel-default" class=request_<%= request.id %>>
      <div class="panel-heading">
        <h3 class="panel-title">
          <stong><%= link_to request.title, user_request_path(request.user.id, request.id) %></strong>
        </h3>
      </div>
      <div class="panel-body">
        <%= link_to 'Edit Request', edit_user_request_path(request.user.id, request.id), class: 'btn btn-large btn-warning' %>
        <%= link_to 'Delete Request', user_request_path(request.user.id, request.id), method: "delete", class: 'btn btn-large btn-danger' %>
        <h3>Offers:</h3>


        <div class="offer">
          <% request.offers.each do |offer| %>
            <h4><%= User.find(offer.user_id).first_name %> has offered to help!</h4>
            <h4> Offer Status: <%= offer.status %> </h4>
            <%= button_to 'Accept Offer', accept_offer_path(offer),  class: 'btn btn-large btn-primary'%>
            <%= button_to 'Decline Offer', decline_offer_path(offer), class: 'btn btn-large btn-danger' %>
          <% end %>
        </div>




      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/requests/new.html.erb
<h1> Create a Request for Help </h1>

<%= render "form" %>

app/views/requests/request_dashboard.html.erb
<h1> All Requests </h1>

<%= week_calendar attribute: :start_time, events: @requests do |date, requests| %>
  <%= date %>
  <% requests.each do |request| %>
    <p><%= link_to request.title, view_request_path(request) %> @ <%= request.time %></p>
  <% end %>
<% end %>

<div class="request-container container-fluid">
  <% @requests.each do |request| %>
  <div class="panel panel-default" class=request_<%= request.id %>>
    <div class="panel-heading">
      <h3 class="panel-title">
        <stong>
          <h1> Title: <%= request.title %> </h1>
          <h1> Requested By: <%= request.user.first_name %>
        </strong>
      </h3>
    </div>
    <div class="panel-body">
      <h3> When: <%= request.date %> @ <%= request.time %> </h3>
      <h3> Time Requested: <%= request.duration %> hours </h3>
      <h3> Location: <%= request.location %> </h3>
      <h3> Description: <%= request.description %> </h3>

      <h3> Offers to Help: </h3>
      <% request.offers.each do |offer| %>
        <p> <%= offer.user.first_name %>: I can help! </p>
      <% end %>

      <%= button_to "Offer Help", user_offers_path(current_user, request_id: request.id), class: 'btn btn-large btn-warning' %>
    </div>
  </div>
  <% end %>
</div>

app/views/requests/show.html.erb
<div class="offer-container container-fluid">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <h3><strong> Request Title: <%= @request.title %> </strong><br></h3>
        <h3>Requested By: <%= User.find(@request.user_id).first_name %></h3>
        <h3>Description: <%= @request.description %></h3>
      </div>
    </div>
    <div class="panel-body">
      <h4> When: <%= request.date %> @ <%= request.time %> </h4>
      <h4> Start At: <%= @request.start_time %> </h4>
      <h4> Requested Duration: <%= @request.duration %> hours </h4>
      <h4> Location Requested: <%= @request.location %> </h4>
      <% @request.offers.each do |offer| %>
        <h4> <%= User.find(offer.user_id).first_name %> </h4>
        <h4> Offer Status: <%= offer.status_of_offer %> </h4>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/view_request.html.erb
<div class="offer-container container-fluid">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <strong> Request Title: <%= @request.title %> </strong><br>
        Requested By: <%= User.find(@request.user_id).first_name %><br>
        Description: <%= @request.description %>
      </h3>
    </div>
    <div class="panel-body">
      <h3> When: <%= @request.date %> @ <%= @request.time %> </h3>
      <h3> Start At: <%= @request.start_time %> </h3>
      <h3> Requested Duration: <%= @request.duration %> hours </h3>
      <h3> Location Requested: <%= @request.location %> </h3>
      <% @request.offers.each do |offer| %>
        <h3> <%= User.find(offer.user_id).first_name %> </h3>
        <h3> Offer Status: <%= offer.status %> </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pearing</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Requests<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Requests", user_requests_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "View All Requests", requests_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Request", new_user_request_path(current_user) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offers<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Offers", user_offers_path(current_user) %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_guest_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pearing</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Create Account", new_user_path %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navigation.html.erb
<% if !current_user %>
    <%= render 'shared/guest_nav' %>
<% elsif current_user.default? %>
   <%= render 'shared/user_nav' %>
<% elsif current_user.admin? %>
  <%= render 'shared/admin_nav' %>
<% end %>

app/views/shared/_user_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pearing</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Requests<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Requests", user_requests_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "View All Requests", requests_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Request", new_user_request_path(current_user) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offers<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Offers", user_offers_path(current_user) %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :slack_handle %>
  <%= f.text_field :slack_handle %>

  <%= f.label :cohort %>
  <%= f.number_field :cohort %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.username %>! </h1>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to Pearing App!</h1>
  <p class="lead">This is an application intended to help students at Turing schedule pairing sessions with students in other cohorts.</p>
</div>